<a href="https://colab.research.google.com/github/LOHITHA-SRI4517/DAE-NUMPY/blob/main/PRACTICE_QNAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.array([10,20,30])
print(a)

[10 20 30]


**2.Create an array of 5 languages**

In [ ]:
pip install numpy

In [ ]:
import numpy as np
languages=np.array(["C","C++","Java","Mongo DB","Python"])
print(languages)

['C' 'C++' 'Java' 'Mongo DB' 'Python']


3.Create 3*4 matrix with all zeroes(Zero Matrix)

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.zeros((3,4),dtype=int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


4. Create 2x3x5 matrix and find dimenisions of the matrix

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.zeros((2,3,5),dtype=int)
print(a)
print(a.ndim)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]
3


5.Create Identity Matrix of 4x4

In [ ]:
pip install numpy

In [ ]:
import numpy as np
matrix=np.ones((4,4),dtype=int)
print(matrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


6.Create 5 random numbers btw 1 to 100 using randit function

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.random.randint(1,101,size=5)
print(a)

[43 90 51 94 29]


7.Create a 3x3 matrix  random with all values as floating point

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.random.rand(3,3)
print(a)

[[0.73716668 0.5078712  0.20037471]
 [0.80126774 0.57590701 0.85614394]
 [0.46255809 0.55312901 0.14177979]]


8.Create a 3x3 matrix with all integer values

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.random.randint(1,101,size=(3,3))
print(a)

[[97 44  1]
 [58 12  3]
 [15  4 19]]


9. Create 2D array and print elements in it

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.array([[4,5,6],[7,8,9]])
print(a)
print(a[1][1])

[[4 5 6]
 [7 8 9]]
8


10. Create 3D array and print elements in it

In [ ]:
pip install  numpy

In [ ]:
import numpy as np
a=np.array([[[4,5,6],[7,8,9]],[[10,20,30],[40,50,60]]])
print(a)
print(a[1][1][2])

[[[ 4  5  6]
  [ 7  8  9]]

 [[10 20 30]
  [40 50 60]]]
60


11. Create Identity Matrix

In [ ]:
pip install numpy

In [ ]:
import numpy as np
matrix=np.eye(3,dtype=int)
print(matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


12 Create identity matrix of 5(5I)

In [ ]:
pip install numpy

In [ ]:

import numpy as np
matrix=np.eye(3,dtype=int)*5
print(matrix)

[[5 0 0]
 [0 5 0]
 [0 0 5]]


13. Create an array of numbers btw 1 to 100 with same difference

In [ ]:
pip install numpy

In [ ]:
import numpy as np
array=np.arange(1,101,2)
print(array)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


14. Create 15 numbers btw 1 to 100

In [ ]:
pip install numpy

In [ ]:
import numpy as np
array=np.linspace(1,101,15,dtype=int)
print(array)

[  1   8  15  22  29  36  43  51  58  65  72  79  86  93 101]
