<a href="https://colab.research.google.com/github/LOHITHA-SRI4517/DAE-NUMPY/blob/main/PS_GFG_PRACTICE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Converting a List into Array

In [ ]:
pip install numpy

In [ ]:
import numpy as np
lst=[1,2,3,4]
print(type(lst))
print(np.array(lst))
print(type(np.array(lst)))

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


2. Printing array with user defined dimensions

In [ ]:
pip install numpy

In [ ]:
import numpy as np
lst=[1,2,3,4]
arr=np.array(lst,ndmin=1)
a=np.array(lst,ndmin=2)
print(arr)
print(a)

[1 2 3 4]
[[1 2 3 4]]


2. Arange Function

In [ ]:
pip install numpy

In [ ]:
import numpy as np
num=np.arange(0,101,2)
print(num)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


3. Multi Dimension Array

In [ ]:
pip install numpy

In [ ]:
import numpy as np
a=np.array([[1,2,3], [4,5,6], [10,20,30], [40,50,60]])
print(a.ndim)

2


4. Size Function


    *In python numpy.size() function counts the no. of elements alog the axis (0-Rows,1-Columns)*


In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6], [10,20,30], [40,50,60]])
print(arr)
print("TOTAL : ",arr.size)
print("ROWS : ",np.size(arr,0))
print("COLUMNS :",np.size(arr,1))

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
TOTAL :  12
ROWS :  4
COLUMNS : 3


4. Shape Function

The shape function of an array is defined as number of elements in each dimension.Dimension is the no of indices or subscripts

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6], [10,20,30], [40,50,60]])
print(arr)
print(a.shape)
#print((np.size(arr,0),np.size(arr,1)))

[[ 1  2  3]
 [ 4  5  6]
 [10 20 30]
 [40 50 60]]
(4, 3)
(4, 3)


5.Dtype Function

It tells us what type of data is stored inside a NumPy array.

Every NumPy array has a dtype.

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6], [10,20,30], [40,50,60]])
print(arr.dtype)

int64


6. ndim function

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6]])
print(arr.ndim)
arr1=np.array(arr, ndmin=4)
print(arr1)

2
[[[[1 2 3]
   [4 5 6]]]]


8. Zeros Function

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.zeros((3,4),dtype=int)
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


9. Ones Function

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.ones((4,4),dtype=int)
print(arr)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


10. Identity Matrix

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.eye(4,dtype=int)
print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


10. Empty Function

In [ ]:
pip install numpy


In [ ]:
import numpy as np
#arr=np.array([[1,2,3], [4,5,6], [10,20,30], [40,50,60]])
np.empty(shape=(2,3))

array([[2.59245927e-315, 0.00000000e+000, 6.87509924e-310],
       [6.87509924e-310, 6.87509928e-310, 6.87511065e-310]])

11. Basic Array Operations

In [ ]:
pip install numpy

In [ ]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6]])
print(arr)
print('-' * 10)
print(arr+1)  #Adds 1 to each element

[[1 2 3]
 [4 5 6]]
----------
[[2 3 4]
 [5 6 7]]
