<a href="https://colab.research.google.com/github/LOHITHA-SRI4517/DAE-NUMPY/blob/main/WEEK_3(FINAL).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.**EXPANDING AN ARRAY Using Axis concept**

In [1]:
pip install numpy

In [4]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a.ndim)
b=np.expand_dims(a,axis=1)
print("After Expanding :",b.ndim)

1
After Expanding : 2


2.**Expanding An Array Without Axis**

In [5]:
pip install numpy

In [9]:
import numpy as np
arr=np.array([[1,2,3], [4,5,6]])
print(arr.ndim)
arr1=np.array(arr, ndmin=4)
print(arr1)
print("After Expanding :",arr1.ndim)

2
[[[[1 2 3]
   [4 5 6]]]]
After Expanding : 4


3. **Squeezing the array**

In [10]:
pip install numpy

In [19]:
import numpy as np
a=np.array(10)
print("Dimension of array:",a.ndim)
b=np.expand_dims(a,axis=0)
print("after expanding dimension is:",b.ndim)
print(b)
c=np.squeeze(b)
print("Dimension after Squeesing is :",c.ndim)

Dimension of array: 0
after expanding dimension is: 1
[10]
Dimension after Squeesing is : 0


4. **Sorting 1D Array**

In [11]:
pip install numpy

In [15]:
import numpy as np
s=np.array([40,20,1,35,80])
print("Ascending Order:",np.sort(s)) #ascending order
print("Descending Order:",np.sort(s)[::-1])#descending order

Ascending Order: [ 1 20 35 40 80]
Descending Order: [80 40 35 20  1]


## **Sorting a 2D NumPy Array**

When sorting a 2D array, you can specify the `axis` along which to sort:

*   `axis=0`: Sorts along the columns (each column is sorted independently).
*   `axis=1`: Sorts along the rows (each row is sorted independently).
*   `axis=None` (default): Flattens the array first, then sorts it as a 1D array.

In [20]:
import numpy as np

arr_2d = np.array([[3, 1, 4],
                   [6, 5, 2],
                   [9, 7, 8]])

print("Original 2D Array:")
print(arr_2d)

print("\nSorted along axis=0 (columns):")
print(np.sort(arr_2d, axis=0))

print("\nSorted along axis=1 (rows):")
print(np.sort(arr_2d, axis=1))

print("\nSorted after flattening (axis=None):")
print(np.sort(arr_2d, axis=None))

Original 2D Array:
[[3 1 4]
 [6 5 2]
 [9 7 8]]

Sorted along axis=0 (columns):
[[3 1 2]
 [6 5 4]
 [9 7 8]]

Sorted along axis=1 (rows):
[[1 3 4]
 [2 5 6]
 [7 8 9]]

Sorted after flattening (axis=None):
[1 2 3 4 5 6 7 8 9]
